//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdravoKorporacija.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZdravoKorporacija.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergies:.
        /// </summary>
        public static string AlergijeText {
            get {
                return ResourceManager.GetString("AlergijeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Choose Alternatives:.
        /// </summary>
        public static string AlternativniBtn {
            get {
                return ResourceManager.GetString("AlternativniBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives.
        /// </summary>
        public static string AlternativniGrid {
            get {
                return ResourceManager.GetString("AlternativniGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives:.
        /// </summary>
        public static string AlternativniText {
            get {
                return ResourceManager.GetString("AlternativniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string BrojTelefonaText {
            get {
                return ResourceManager.GetString("BrojTelefonaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        public static string DaBtn {
            get {
                return ResourceManager.GetString("DaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Date.
        /// </summary>
        public static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DatumGrid {
            get {
                return ResourceManager.GetString("DatumGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time:.
        /// </summary>
        public static string DatumIVremeText {
            get {
                return ResourceManager.GetString("DatumIVremeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Dose:.
        /// </summary>
        public static string DnevnaDozaText {
            get {
                return ResourceManager.GetString("DnevnaDozaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue an Anamnesis.
        /// </summary>
        public static string DodajAnamnezuBtn {
            get {
                return ResourceManager.GetString("DodajAnamnezuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string DodajBtn {
            get {
                return ResourceManager.GetString("DodajBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        public static string DozaGrid {
            get {
                return ResourceManager.GetString("DozaGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string HitnoGrid {
            get {
                return ResourceManager.GetString("HitnoGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ImeGrid {
            get {
                return ResourceManager.GetString("ImeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ImeText {
            get {
                return ResourceManager.GetString("ImeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Date.
        /// </summary>
        public static string IzaberiDatumText {
            get {
                return ResourceManager.GetString("IzaberiDatumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete an Anamnesis.
        /// </summary>
        public static string IzbrisiAnamnezuBtn {
            get {
                return ResourceManager.GetString("IzbrisiAnamnezuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete a Request.
        /// </summary>
        public static string IzbrisiZahtevBtn {
            get {
                return ResourceManager.GetString("IzbrisiZahtevBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Issue a Prescription.
        /// </summary>
        public static string IzdajReceptBtn {
            get {
                return ResourceManager.GetString("IzdajReceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Issue a Referral Request .
        /// </summary>
        public static string IzdajUputBtn {
            get {
                return ResourceManager.GetString("IzdajUputBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string IzmeniBtn {
            get {
                return ResourceManager.GetString("IzmeniBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit an Appointment.
        /// </summary>
        public static string IzmeniTerminBtn {
            get {
                return ResourceManager.GetString("IzmeniTerminBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit a Referral Request.
        /// </summary>
        public static string IzmeniUputBtn {
            get {
                return ResourceManager.GetString("IzmeniUputBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit a Request.
        /// </summary>
        public static string IzmeniZahtevBtn {
            get {
                return ResourceManager.GetString("IzmeniZahtevBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Report.
        /// </summary>
        public static string IzvestajiBtn {
            get {
                return ResourceManager.GetString("IzvestajiBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Language.
        /// </summary>
        public static string JezikMenu {
            get {
                return ResourceManager.GetString("JezikMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Identity Number.
        /// </summary>
        public static string JMBGGrid {
            get {
                return ResourceManager.GetString("JMBGGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Number:.
        /// </summary>
        public static string JMBGText {
            get {
                return ResourceManager.GetString("JMBGText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string KorisnickoImeText {
            get {
                return ResourceManager.GetString("KorisnickoImeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type:.
        /// </summary>
        public static string KrvnaGrupaText {
            get {
                return ResourceManager.GetString("KrvnaGrupaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Choose Doctors.
        /// </summary>
        public static string LekariBtn {
            get {
                return ResourceManager.GetString("LekariBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor:.
        /// </summary>
        public static string LekarText {
            get {
                return ResourceManager.GetString("LekarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string LekGrid {
            get {
                return ResourceManager.GetString("LekGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LozinkaText {
            get {
                return ResourceManager.GetString("LozinkaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string NazivGrid {
            get {
                return ResourceManager.GetString("NazivGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Name:.
        /// </summary>
        public static string NazivLekaText {
            get {
                return ResourceManager.GetString("NazivLekaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        public static string NeBtn {
            get {
                return ResourceManager.GetString("NeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Number of Necessary Confirmations:.
        /// </summary>
        public static string NeophodneBtn {
            get {
                return ResourceManager.GetString("NeophodneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Necessary Confirmations.
        /// </summary>
        public static string NeophodneGrid {
            get {
                return ResourceManager.GetString("NeophodneGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Medicine:.
        /// </summary>
        public static string NoviLekText {
            get {
                return ResourceManager.GetString("NoviLekText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Effects:.
        /// </summary>
        public static string NusPojaveText {
            get {
                return ResourceManager.GetString("NusPojaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string ObrisiBtn {
            get {
                return ResourceManager.GetString("ObrisiBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete a Prescription.
        /// </summary>
        public static string ObrisiReceptBtn {
            get {
                return ResourceManager.GetString("ObrisiReceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete a Referral Request.
        /// </summary>
        public static string ObrisiUputBtn {
            get {
                return ResourceManager.GetString("ObrisiUputBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the request?.
        /// </summary>
        public static string ObrisiZahtevDialog {
            get {
                return ResourceManager.GetString("ObrisiZahtevDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Logout.
        /// </summary>
        public static string OdjaviSeMenu {
            get {
                return ResourceManager.GetString("OdjaviSeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlT+L.
        /// </summary>
        public static string OdjaviSeToolTip {
            get {
                return ResourceManager.GetString("OdjaviSeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Approve a Request.
        /// </summary>
        public static string OdobriZahtevBtn {
            get {
                return ResourceManager.GetString("OdobriZahtevBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string OdustaniBtn {
            get {
                return ResourceManager.GetString("OdustaniBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string OpisGrid {
            get {
                return ResourceManager.GetString("OpisGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string OpisText {
            get {
                return ResourceManager.GetString("OpisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        public static string OsnovniPodaciText {
            get {
                return ResourceManager.GetString("OsnovniPodaciText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel an Appointment.
        /// </summary>
        public static string OtkaziTerminBtn {
            get {
                return ResourceManager.GetString("OtkaziTerminBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the appointment?.
        /// </summary>
        public static string OtkaziTerminDialog {
            get {
                return ResourceManager.GetString("OtkaziTerminDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this referral request?.
        /// </summary>
        public static string OtkaziUputDialog {
            get {
                return ResourceManager.GetString("OtkaziUputDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Patients.
        /// </summary>
        public static string PacijentiMenu {
            get {
                return ResourceManager.GetString("PacijentiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+P.
        /// </summary>
        public static string PacijentiToolTip {
            get {
                return ResourceManager.GetString("PacijentiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        public static string PacijentText {
            get {
                return ResourceManager.GetString("PacijentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string PocetakGrid {
            get {
                return ResourceManager.GetString("PocetakGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teraphy Start:.
        /// </summary>
        public static string PocetakTerapijeText {
            get {
                return ResourceManager.GetString("PocetakTerapijeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string PocetakText {
            get {
                return ResourceManager.GetString("PocetakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string PodesavanjaMenu {
            get {
                return ResourceManager.GetString("PodesavanjaMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+S.
        /// </summary>
        public static string PodesavanjaToolTip {
            get {
                return ResourceManager.GetString("PodesavanjaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string PolGrid {
            get {
                return ResourceManager.GetString("PolGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string PolText {
            get {
                return ResourceManager.GetString("PolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Confirm.
        /// </summary>
        public static string PotvrdiBtn {
            get {
                return ResourceManager.GetString("PotvrdiBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string PotvrdiloGrid {
            get {
                return ResourceManager.GetString("PotvrdiloGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PrezimeGrid {
            get {
                return ResourceManager.GetString("PrezimeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string PrezimeText {
            get {
                return ResourceManager.GetString("PrezimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string ProizvodjacGrid {
            get {
                return ResourceManager.GetString("ProizvodjacGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacterer:.
        /// </summary>
        public static string ProizvodjacText {
            get {
                return ResourceManager.GetString("ProizvodjacText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string ProstorijaGrid {
            get {
                return ResourceManager.GetString("ProstorijaGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        public static string ProstorijaText {
            get {
                return ResourceManager.GetString("ProstorijaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients:.
        /// </summary>
        public static string SastojciText {
            get {
                return ResourceManager.GetString("SastojciText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms.
        /// </summary>
        public static string SimptomiGrid {
            get {
                return ResourceManager.GetString("SimptomiGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms:.
        /// </summary>
        public static string SimptomiText {
            get {
                return ResourceManager.GetString("SimptomiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark Theme.
        /// </summary>
        public static string TemaMenu {
            get {
                return ResourceManager.GetString("TemaMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Appointments.
        /// </summary>
        public static string TerminiMenu {
            get {
                return ResourceManager.GetString("TerminiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+A.
        /// </summary>
        public static string TerminiToolTip {
            get {
                return ResourceManager.GetString("TerminiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TipGrid {
            get {
                return ResourceManager.GetString("TipGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TipText {
            get {
                return ResourceManager.GetString("TipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string TrajanjeGrid {
            get {
                return ResourceManager.GetString("TrajanjeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration(days):.
        /// </summary>
        public static string TrajanjeText {
            get {
                return ResourceManager.GetString("TrajanjeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Referral letters.
        /// </summary>
        public static string UputiMenu {
            get {
                return ResourceManager.GetString("UputiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+R.
        /// </summary>
        public static string UputiToolTip {
            get {
                return ResourceManager.GetString("UputiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrals for Stationary Treatment.
        /// </summary>
        public static string UputiZaStacionarnoGrid {
            get {
                return ResourceManager.GetString("UputiZaStacionarnoGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT+N.
        /// </summary>
        public static string ZahteviToolTip {
            get {
                return ResourceManager.GetString("ZahteviToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Medicine Requests.
        /// </summary>
        public static string ZahteviZaLekoveMenu {
            get {
                return ResourceManager.GetString("ZahteviZaLekoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make an Emergency Appointment.
        /// </summary>
        public static string ZakaziHitniBtn {
            get {
                return ResourceManager.GetString("ZakaziHitniBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make an Appointment.
        /// </summary>
        public static string ZakaziTerminBtn {
            get {
                return ResourceManager.GetString("ZakaziTerminBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Corporation.
        /// </summary>
        public static string ZdravoKorporacijaMenu {
            get {
                return ResourceManager.GetString("ZdravoKorporacijaMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Medical Record.
        /// </summary>
        public static string ZdravstveniKartonBtn {
            get {
                return ResourceManager.GetString("ZdravstveniKartonBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Record.
        /// </summary>
        public static string ZdravstveniKartonGrid {
            get {
                return ResourceManager.GetString("ZdravstveniKartonGrid", resourceCulture);
            }
        }
    }
}
